name: tests
on:
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash -euo pipefail {0}

jobs:
  test:
    name: Run tests
    runs-on: [ self-hosted, gen3, large ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.1'

      - name: set custom docker config directory
        uses: ./.github/actions/set-docker-config-dir

      - uses: docker/setup-buildx-action@v3

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.NEON_DOCKERHUB_USERNAME }}
          password: ${{ secrets.NEON_DOCKERHUB_PASSWORD }}

      - name: Check dependencies
        run: |
          go version
          docker version
          docker buildx version

      - name: Build go-chef
        run: |
          make build

      - name: Run tests
        run: |
          make test
